package com.example.gpgrocery.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color
import com.example.gpgrocery.data.model.Category

/**
 * The Crate palette: basil green and tangerine on a cool, slightly green mist.
 *
 * Material's [androidx.compose.material3.ColorScheme] covers what its own
 * components draw. Everything else the screens need (stock warnings, the
 * category tiles, the hero card, chart colours) lives here, so a screen never
 * reaches for a raw hex value.
 */
@Immutable
data class CrateColors(
    val isDark: Boolean,
    val background: Color,
    val surface: Color,
    val surfaceSunken: Color,
    val line: Color,
    val divider: Color,
    val fieldLine: Color,
    val ink: Color,
    val inkSoft: Color,
    val inkMuted: Color,
    val primary: Color,
    val onPrimary: Color,
    val primarySoft: Color,
    val onPrimarySoft: Color,
    val primaryStrong: Color,
    val outlineAccent: Color,
    val hero: Color,
    val onHero: Color,
    val heroLine: Color,
    val heroChip: Color,
    val accent: Color,
    val warningSoft: Color,
    val onWarning: Color,
    val warningCard: Color,
    val warningCardLine: Color,
    val warningTile: Color,
    val warningDot: Color,
    val dangerSoft: Color,
    val onDanger: Color,
    val dangerDot: Color,
    val chartMuted: Color,
    val chipSelected: Color,
    val onChipSelected: Color,
    val scrim: Color,
    val categories: Map<Category, CategoryColors>,
    val chartCategories: Map<Category, Color>,
) {
    fun category(category: Category): CategoryColors = categories.getValue(category)
}

@Immutable
data class CategoryColors(val container: Color, val content: Color)

val LightCrateColors = CrateColors(
    isDark = false,
    background = Color(0xFFF3F5F2),
    surface = Color(0xFFFFFFFF),
    surfaceSunken = Color(0xFFE4EAE6),
    line = Color(0xFFE3E8E4),
    divider = Color(0xFFEEF1EE),
    fieldLine = Color(0xFFD5DDD7),
    ink = Color(0xFF14201A),
    inkSoft = Color(0xFF3E4A43),
    inkMuted = Color(0xFF5B6760),
    primary = Color(0xFF1E6B45),
    onPrimary = Color(0xFFFFFFFF),
    primarySoft = Color(0xFFDCEFE3),
    onPrimarySoft = Color(0xFF12492F),
    primaryStrong = Color(0xFF155A38),
    outlineAccent = Color(0xFFB9D3C3),
    hero = Color(0xFF1E6B45),
    onHero = Color(0xFFFFFFFF),
    heroLine = Color(0xFF9FE0B8),
    heroChip = Color(0x29FFFFFF),
    accent = Color(0xFFF07F1A),
    warningSoft = Color(0xFFFFF0D9),
    onWarning = Color(0xFF8A4B00),
    warningCard = Color(0xFFFFF6E9),
    warningCardLine = Color(0xFFF5DDB6),
    warningTile = Color(0xFFFFE3BD),
    warningDot = Color(0xFFE08A1E),
    dangerSoft = Color(0xFFFDE7E5),
    onDanger = Color(0xFFA1231B),
    dangerDot = Color(0xFFC8372D),
    chartMuted = Color(0xFFB9D9C6),
    chipSelected = Color(0xFF14201A),
    onChipSelected = Color(0xFFFFFFFF),
    scrim = Color(0x6614201A),
    categories = mapOf(
        Category.PRODUCE to CategoryColors(Color(0xFFE3F3E5), Color(0xFF1E6B45)),
        Category.DAIRY to CategoryColors(Color(0xFFE6EEF9), Color(0xFF2F5E9E)),
        Category.BAKERY to CategoryColors(Color(0xFFFBEBD8), Color(0xFFA45A12)),
        Category.PANTRY to CategoryColors(Color(0xFFF1E8DA), Color(0xFF7A5A2E)),
        Category.DRINKS to CategoryColors(Color(0xFFE4F1F4), Color(0xFF1F6E7E)),
        Category.FROZEN to CategoryColors(Color(0xFFECEAF7), Color(0xFF5B4DA0)),
        Category.SNACKS to CategoryColors(Color(0xFFFFF1D6), Color(0xFF9A6A00)),
        Category.HOUSEHOLD to CategoryColors(Color(0xFFF4E6EF), Color(0xFF8E3B6B)),
    ),
    chartCategories = mapOf(
        Category.PRODUCE to Color(0xFF1E6B45),
        Category.DAIRY to Color(0xFF2F7FC1),
        Category.PANTRY to Color(0xFFF07F1A),
        Category.BAKERY to Color(0xFFA45A12),
        Category.DRINKS to Color(0xFF7FC8A9),
        Category.FROZEN to Color(0xFF6B4FA0),
        Category.SNACKS to Color(0xFFE3B341),
        Category.HOUSEHOLD to Color(0xFFB0578D),
    ),
)

val DarkCrateColors = CrateColors(
    isDark = true,
    background = Color(0xFF0E1511),
    surface = Color(0xFF17211B),
    surfaceSunken = Color(0xFF1F2B24),
    line = Color(0xFF243128),
    divider = Color(0xFF243128),
    fieldLine = Color(0xFF34443A),
    ink = Color(0xFFE8EFEA),
    inkSoft = Color(0xFFC6D2CA),
    inkMuted = Color(0xFFA3B1A8),
    primary = Color(0xFF6FD39B),
    onPrimary = Color(0xFF07210F),
    primarySoft = Color(0xFF1D4A33),
    onPrimarySoft = Color(0xFF9FE0B8),
    primaryStrong = Color(0xFF8EE0B0),
    outlineAccent = Color(0xFF2F6A4A),
    hero = Color(0xFF1D4A33),
    onHero = Color(0xFFFFFFFF),
    heroLine = Color(0xFF6FD39B),
    heroChip = Color(0x1FFFFFFF),
    accent = Color(0xFFFFA24C),
    warningSoft = Color(0xFF3A2A12),
    onWarning = Color(0xFFFFB866),
    warningCard = Color(0xFF231C10),
    warningCardLine = Color(0xFF4A3818),
    warningTile = Color(0xFF4A3818),
    warningDot = Color(0xFFFFA24C),
    dangerSoft = Color(0xFF3D1A17),
    onDanger = Color(0xFFFF9A8F),
    dangerDot = Color(0xFFFF7A6E),
    chartMuted = Color(0xFF2F5A43),
    chipSelected = Color(0xFFE8EFEA),
    onChipSelected = Color(0xFF0E1511),
    scrim = Color(0x99000000),
    categories = mapOf(
        Category.PRODUCE to CategoryColors(Color(0xFF1C3326), Color(0xFF7FD3A0)),
        Category.DAIRY to CategoryColors(Color(0xFF1B2A40), Color(0xFF8DB5EC)),
        Category.BAKERY to CategoryColors(Color(0xFF3A2A18), Color(0xFFF0B070)),
        Category.PANTRY to CategoryColors(Color(0xFF342A1C), Color(0xFFD9B98A)),
        Category.DRINKS to CategoryColors(Color(0xFF16323A), Color(0xFF7CC9D8)),
        Category.FROZEN to CategoryColors(Color(0xFF26223F), Color(0xFFB3A6F0)),
        Category.SNACKS to CategoryColors(Color(0xFF3A2F12), Color(0xFFF2C94C)),
        Category.HOUSEHOLD to CategoryColors(Color(0xFF3A1E30), Color(0xFFE59BC7)),
    ),
    chartCategories = mapOf(
        Category.PRODUCE to Color(0xFF6FD39B),
        Category.DAIRY to Color(0xFF7FB4EC),
        Category.PANTRY to Color(0xFFFFA24C),
        Category.BAKERY to Color(0xFFD08A45),
        Category.DRINKS to Color(0xFF3F8F79),
        Category.FROZEN to Color(0xFFA897F0),
        Category.SNACKS to Color(0xFFF2C94C),
        Category.HOUSEHOLD to Color(0xFFD77BB0),
    ),
)

internal val LightScheme = lightColorScheme(
    primary = LightCrateColors.primary,
    onPrimary = LightCrateColors.onPrimary,
    primaryContainer = LightCrateColors.primarySoft,
    onPrimaryContainer = LightCrateColors.onPrimarySoft,
    secondary = LightCrateColors.accent,
    onSecondary = Color(0xFF1B1206),
    secondaryContainer = LightCrateColors.primarySoft,
    onSecondaryContainer = LightCrateColors.onPrimarySoft,
    background = LightCrateColors.background,
    onBackground = LightCrateColors.ink,
    surface = LightCrateColors.surface,
    onSurface = LightCrateColors.ink,
    surfaceVariant = LightCrateColors.surfaceSunken,
    onSurfaceVariant = LightCrateColors.inkMuted,
    surfaceContainerLowest = Color.White,
    surfaceContainerLow = Color(0xFFF8FAF7),
    surfaceContainer = Color(0xFFFFFFFF),
    surfaceContainerHigh = Color(0xFFFFFFFF),
    surfaceContainerHighest = LightCrateColors.surfaceSunken,
    outline = LightCrateColors.fieldLine,
    outlineVariant = LightCrateColors.line,
    error = LightCrateColors.onDanger,
    onError = Color.White,
    errorContainer = LightCrateColors.dangerSoft,
    onErrorContainer = LightCrateColors.onDanger,
    scrim = Color(0xFF14201A),
)

internal val DarkScheme = darkColorScheme(
    primary = DarkCrateColors.primary,
    onPrimary = DarkCrateColors.onPrimary,
    primaryContainer = DarkCrateColors.primarySoft,
    onPrimaryContainer = DarkCrateColors.onPrimarySoft,
    secondary = DarkCrateColors.accent,
    onSecondary = Color(0xFF2A1600),
    secondaryContainer = DarkCrateColors.primarySoft,
    onSecondaryContainer = DarkCrateColors.onPrimarySoft,
    background = DarkCrateColors.background,
    onBackground = DarkCrateColors.ink,
    surface = DarkCrateColors.surface,
    onSurface = DarkCrateColors.ink,
    surfaceVariant = DarkCrateColors.surfaceSunken,
    onSurfaceVariant = DarkCrateColors.inkMuted,
    surfaceContainerLowest = DarkCrateColors.background,
    surfaceContainerLow = Color(0xFF131C17),
    surfaceContainer = DarkCrateColors.surface,
    surfaceContainerHigh = Color(0xFF1C2821),
    surfaceContainerHighest = DarkCrateColors.surfaceSunken,
    outline = DarkCrateColors.fieldLine,
    outlineVariant = DarkCrateColors.line,
    error = DarkCrateColors.onDanger,
    onError = Color(0xFF3D0B07),
    errorContainer = DarkCrateColors.dangerSoft,
    onErrorContainer = DarkCrateColors.onDanger,
    scrim = Color.Black,
)
